branch-defaults:
  default:
    environment: udagram-dev
    group_suffix: null
deploy:
  artifact: ./www/archive.zip
global:
  application_name: udagram-dev
  branch: null
  default_ec2_keyname: udagram-dev
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udacity
  repository: null
  sc: null
  workspace_type: Application
